<?xml version="1.0"?>
<package format="3">
  <name>g1eus</name>
  <version>0.0.0</version>
  <description>EusLisp interface for Unitree G1 Robot.</description>

  <maintainer email="tsubaki@jsk.t.u-tokyo.ac.jp">Michitoshi Tsubaki</maintainer>
  <author email="tsubaki@jsk.t.u-tokyo.ac.jp">Michitoshi Tsubaki</author>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>builtin_interfaces</depend>
  <depend>control_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>roseus</depend>
  <depend>sensor_msgs</depend>
  <depend>trajectory_msgs</depend>

  <exec_depend>g1_description</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
